---

 - name: yum install openstack repo
   yum: name="centos-release-openstack-liberty" state=present

 - name: yum install dependencies
   yum: name={{ item }} state=present
   with_items:
     - "python-openstackclient"
     - "python-novaclient"
     - "python-keystoneclient"
     - "python-heatclient"
     - "python-swiftclient"
     - "python-neutronclient"
     - "python-cinderclient"
     - "python-glanceclient"

 - name: set suspend program
   lineinfile: 
     line: "SuspendProgram=/home/slurm/suspend_prog.sh" 
     dest: /etc/slurm/slurm.conf 
     regexp: '^#SuspendProgram|^SuspendProgram'
     state: present

 - name: set resume program
   lineinfile: 
     line: "ResumeProgram=/home/slurm/resume_prog.sh" 
     dest: /etc/slurm/slurm.conf 
     regexp: '^#ResumeProgram|^ResumeProgram'
     state: present

 - name: set slurm suspend/resume timing parameters
   lineinfile: 
     line: "{{ item.line }}"
     dest: /etc/slurm/slurm.conf 
     regexp: "{{ item.regexp }}"
     state: present
   with_items:
     - { line: "#SuspendTime=" , regexp: "^#SuspendTime|^SuspendTime" }
     - { line: "#SuspendRate=" , regexp: "^#SuspendRate|^SuspendRate" }
     - { line: "#ResumeRate=" , regexp: "^#ResumeRate|^ResumeRate" }
     - { line: "#SuspendTimeout=" , regexp: "^#SuspendTimeout|^SuspendTimeout" }
     - { line: "#ResumeTimeout=" , regexp: "^#ResumeTimeout|^ResumeTimeout" }
     - { line: "#BatchStartTimeout=" , regexp: "^#BatchStartTimeout|^BatchStartTimeout" }


 - name: copy openrc, suspend, and resume scripts
   copy: src={{ item.src }} dest={{ item.dest }} owner=slurm mode=644
   with_items:
     - { src: openrc.sh, dest: /home/slurm/openrc.sh }
     - { src: suspend_prog.sh, dest: /home/slurm/suspend_prog.sh }
     - { src: resume_prog.sh, dest: /home/slurm/resume_prog.sh }

 - name: set suspend and resume scripts executable
   file:
     path: "{{ item }}"
     mode: 0755
     owner: slurm
     group: slurm
   with_items:
     - "/home/slurm/suspend_prog.sh"
     - "/home/slurm/resume_prog.sh"

 - name: restart slurmctld
   service: name=slurmctld state=restarted enabled=yes

