---

   - template: src=firewall_conf/firewalld.conf dest=/etc/firewalld/firewalld.conf

   - template: src=firewall_conf/zones/internal.xml dest=/etc/firewalld/zones/internal.xml

   - template: src=firewall_conf/zones/public.xml dest=/etc/firewalld/zones/public.xml

   - template: src=firewall_conf/services/slurm.xml dest=/etc/firewalld/services/slurm.xml
 
   - name: restart dbus for firewalld :(
     service: name=dbus state=restarted

   - name: firewalld restart
     service: name=firewalld state=restarted

   - name: add interface to internal zone firewall-cmd
     firewalld:
       zone: internal
       interface: "{{ private_interface }}"
       permanent: yes
       state: enabled

   - name: add interface to external zone firewall-cmd
     firewalld:
       zone: public
       interface: "{{ public_interface }}"
       permanent: yes
       state: enabled

   - name: add slurm to internal zone firewall-cmd
     firewalld:
       zone: internal
       service: slurm
       permanent: yes
       immediate: yes
       state: enabled
